[bot\command_modules\world_state_cmds.py] - 14 issue(s)
  Line 63: Argument of type "object" cannot be assigned to parameter "db_session" of type "AsyncSession" in function "get_entity_by_attributes"
  Line 68: Cannot access attribute "add" for class "object"
  Line 71: Cannot assign to attribute "custom_flags" for class "WorldState"
  Line 73: "__setitem__" method not defined on type "Column[Unknown]"
  Line 76: Cannot access attribute "add" for class "object"
  Line 78: Cannot access attribute "commit" for class "object"
  Line 84: Cannot access attribute "rollback" for class "object"
  Line 107: Argument of type "object" cannot be assigned to parameter "db_session" of type "AsyncSession" in function "get_entity_by_attributes"
  Line 114: "__delitem__" method not defined on type "Column[Unknown]"
  Line 116: Cannot access attribute "add" for class "object"
  Line 118: Cannot access attribute "commit" for class "object"
  Line 124: Cannot access attribute "rollback" for class "object"
  Line 144: Argument of type "object" cannot be assigned to parameter "db_session" of type "AsyncSession" in function "get_entity_by_attributes"
  Line 146: Invalid conditional operand of type "Column[Unknown]"

[tests\commands\test_undo_commands.py] - 14 issue(s)
  Line 66: Expected 1 positional argument
  Line 78: Expected 1 positional argument
  Line 93: Expected 1 positional argument
  Line 116: Parameter "num_steps" is already assigned
  Line 145: Parameter "num_steps" is already assigned
  Line 169: Parameter "num_steps" is already assigned
  Line 187: Parameter "num_steps" is already assigned
  Line 208: Parameter "log_id_target" is already assigned
  Line 231: Parameter "log_id_target" is already assigned
  Line 250: Parameter "log_id_target" is already assigned
  Line 269: Parameter "log_id_target" is already assigned
  Line 286: Parameter "log_id_target" is already assigned
  Line 301: Parameter "num_steps" is already assigned
  Line 314: Argument of type "main" cannot be assigned to parameter "main" of type "Coroutine[Any, Any, _T@run]" in function "run"

[bot\game\managers\mobile_group_manager.py] - 13 issue(s)
  Line 52: Cannot assign to attribute "guild_id" for class "MobileGroup"
  Line 53: Cannot assign to attribute "name_i18n" for class "MobileGroup"
  Line 54: Cannot assign to attribute "description_i18n" for class "MobileGroup"
  Line 55: Cannot assign to attribute "current_location_id" for class "MobileGroup"
  Line 56: Cannot assign to attribute "member_ids" for class "MobileGroup"
  Line 57: Cannot assign to attribute "destination_location_id" for class "MobileGroup"
  Line 58: Cannot assign to attribute "state_variables" for class "MobileGroup"
  Line 59: Cannot assign to attribute "is_active" for class "MobileGroup"
  Line 66: Invalid conditional operand of type "MobileGroup | Column[bool] | ColumnElement[bool] | None"
  Line 103: Invalid conditional operand of type "MobileGroup | ColumnElement[bool] | None"
  Line 123: Invalid conditional operand of type "MobileGroup | ColumnElement[bool] | None"
  Line 124: Cannot assign to attribute "is_active" for class "MobileGroup"
  Line 240: Argument of type "str | None" cannot be assigned to parameter "group_id" of type "str" in function "update_mobile_group"

[tests\game\managers\test_character_manager_data_handling.py] - 13 issue(s)
  Line 84: Cannot access attribute "from_db_dict" for class "type[Character]"
  Line 137: "collected_actions_json" is not a known attribute of "None"
  Line 139: "collected_actions_json" is not a known attribute of "None"
  Line 139: Argument of type "str | None" cannot be assigned to parameter "s" of type "str | bytes | bytearray" in function "loads"
  Line 161: "collected_actions_json" is not a known attribute of "None"
  Line 273: "name_i18n" is not a known attribute of "None"
  Line 274: "skills_data" is not a known attribute of "None"
  Line 275: "abilities_data" is not a known attribute of "None"
  Line 276: "spells_data" is not a known attribute of "None"
  Line 277: "character_class_i18n" is not a known attribute of "None"
  Line 277: Cannot access attribute "character_class_i18n" for class "Character"
  Line 278: "flags" is not a known attribute of "None"
  Line 279: "collected_actions_json" is not a known attribute of "None"

[tests\game\managers\test_item_manager.py] - 13 issue(s)
  Line 96: Invalid conditional operand of type "ColumnElement[bool]"
  Line 97: Invalid conditional operand of type "ColumnElement[bool]"
  Line 98: Invalid conditional operand of type "ColumnElement[bool]"
  Line 99: Invalid conditional operand of type "ColumnElement[bool]"
  Line 100: Invalid conditional operand of type "ColumnElement[bool]"
  Line 101: Invalid conditional operand of type "ColumnElement[bool]"
  Line 102: Invalid conditional operand of type "ColumnElement[bool]"
  Line 106: Object of type "None" is not subscriptable
  Line 107: Object of type "None" is not subscriptable
  Line 108: Object of type "None" is not subscriptable
  Line 109: Object of type "None" is not subscriptable
  Line 178: Invalid conditional operand of type "ColumnElement[bool]"
  Line 179: Invalid conditional operand of type "ColumnElement[bool]"

[tests\game\test_command_router.py] - 13 issue(s)
  Line 157: Argument of type "MockMessage" cannot be assigned to parameter "message" of type "Message" in function "route"
  Line 191: Argument of type "MockMessage" cannot be assigned to parameter "message" of type "Message" in function "route"
  Line 213: Argument of type "MockMessage" cannot be assigned to parameter "message" of type "Message" in function "route"
  Line 232: Cannot assign to attribute "_activate_approved_content" for class "CommandRouter"
  Line 234: Argument of type "MockMessage" cannot be assigned to parameter "message" of type "Message" in function "route"
  Line 237: Cannot access attribute "_activate_approved_content" for class "CommandRouter"
  Line 260: Argument of type "MockMessage" cannot be assigned to parameter "message" of type "Message" in function "route"
  Line 286: Cannot assign to attribute "_activate_approved_content" for class "CommandRouter"
  Line 288: Argument of type "MockMessage" cannot be assigned to parameter "message" of type "Message" in function "route"
  Line 294: Cannot access attribute "_activate_approved_content" for class "CommandRouter"
  Line 318: Cannot access attribute "_activate_approved_content" for class "CommandRouter"
  Line 349: Cannot access attribute "_activate_approved_content" for class "CommandRouter"
  Line 377: Cannot access attribute "_activate_approved_content" for class "CommandRouter"

[tests\integration\test_db_service.py] - 13 issue(s)
  Line 34: Cannot access attribute "_conn_pool" for class "BaseDbAdapter"
  Line 35: Cannot access attribute "_conn_pool" for class "BaseDbAdapter"
  Line 38: Cannot access attribute "_get_raw_connection" for class "BaseDbAdapter"
  Line 41: Cannot access attribute "_conn_pool" for class "BaseDbAdapter"
  Line 42: Cannot access attribute "_conn_pool" for class "BaseDbAdapter"
  Line 50: Cannot access attribute "db" for class "DBService"
  Line 51: Cannot access attribute "db" for class "DBService"
  Line 55: Cannot access attribute "db" for class "DBService"
  Line 56: Cannot access attribute "db" for class "DBService"
  Line 76: Cannot access attribute "_conn_pool" for class "BaseDbAdapter"
  Line 79: Cannot access attribute "_conn_pool" for class "BaseDbAdapter"
  Line 82: Cannot access attribute "db" for class "DBService"
  Line 85: Cannot access attribute "db" for class "DBService"

[bot\command_modules\guild_config_cmds.py] - 12 issue(s)
  Line 38: Cannot access attribute "get" for class "object"
  Line 45: Cannot access attribute "execute" for class "object"
  Line 57: Cannot access attribute "add" for class "object"
  Line 58: Cannot access attribute "commit" for class "object"
  Line 113: Cannot access attribute "execute" for class "object"
  Line 128: Cannot access attribute "add" for class "object"
  Line 129: Cannot access attribute "commit" for class "object"
  Line 132: Cannot access attribute "game_manager" for class "Bot"
  Line 134: Cannot access attribute "game_manager" for class "Bot"
  Line 179: Cannot access attribute "execute" for class "object"
  Line 191: Cannot access attribute "add" for class "object"
  Line 192: Cannot access attribute "commit" for class "object"

[bot\game\utils\stats_calculator.py] - 12 issue(s)
  Line 205: Argument of type "Any | None" cannot be assigned to parameter "x" of type "ConvertibleToInt" in function "__new__"
  Line 205: Argument of type "Any | None" cannot be assigned to parameter "x" of type "ConvertibleToInt" in function "__new__"
  Line 205: Argument of type "Any | None" cannot be assigned to parameter "x" of type "ConvertibleToInt" in function "__new__"
  Line 205: Argument of type "Any | None" cannot be assigned to parameter "x" of type "ConvertibleToInt" in function "__new__"
  Line 208: Argument of type "Any | None" cannot be assigned to parameter "x" of type "ConvertibleToInt" in function "__new__"
  Line 208: Argument of type "Any | None" cannot be assigned to parameter "x" of type "ConvertibleToInt" in function "__new__"
  Line 215: Argument of type "Any | None" cannot be assigned to parameter "x" of type "ConvertibleToFloat" in function "__new__"
  Line 215: Argument of type "Any | None" cannot be assigned to parameter "x" of type "ConvertibleToFloat" in function "__new__"
  Line 215: Argument of type "Any | None" cannot be assigned to parameter "x" of type "ConvertibleToInt" in function "__new__"
  Line 215: Argument of type "Any | None" cannot be assigned to parameter "x" of type "ConvertibleToInt" in function "__new__"
  Line 225: Argument of type "Any | None" cannot be assigned to parameter "x" of type "ConvertibleToInt" in function "__new__"
  Line 225: Argument of type "Any | None" cannot be assigned to parameter "x" of type "ConvertibleToInt" in function "__new__"

[tests\commands\test_party_cmds.py] - 12 issue(s)
  Line 106: Parameter "name" is already assigned
  Line 127: Parameter "name" is already assigned
  Line 138: Parameter "name" is already assigned
  Line 162: Parameter "identifier" is already assigned
  Line 194: Parameter "identifier" is already assigned
  Line 219: Parameter "identifier" is already assigned
  Line 229: Expected 1 positional argument
  Line 243: Expected 1 positional argument
  Line 253: Expected 1 positional argument
  Line 269: Expected 1 positional argument
  Line 304: Parameter "target" is already assigned
  Line 327: Parameter "target" is already assigned

[bot\ai\prompt_context_collector.py] - 11 issue(s)
  Line 87: Cannot access attribute "get_default_bot_language" for class "GameManager"
  Line 328: Cannot access attribute "get_entity_by_conditions" for class "DBService"
  Line 338: Cannot access attribute "get_contextual_lore" for class "LoreManager"
  Line 345: Cannot access attribute "get_default_bot_language" for class "GameManager"
  Line 355: Argument of type "list[Any | str | None]" cannot be assigned to parameter "iterable" of type "Iterable[SupportsRichComparisonT@sorted]" in function "sorted"
  Line 364: Argument of type "List[Ability]" cannot be assigned to parameter "value" of type "bool" in function "__setitem__"
  Line 369: Argument of type "List[Dict[str, Any]]" cannot be assigned to parameter "value" of type "bool" in function "__setitem__"
  Line 397: "Character" is not awaitable
  Line 397: "None" is not awaitable
  Line 418: "Character" is not awaitable
  Line 418: "None" is not awaitable

[bot\database\postgres_adapter.py] - 11 issue(s)
  Line 108: No overloads for "__init__" match the provided arguments
  Line 109: Argument of type "AsyncEngine" cannot be assigned to parameter "bind" of type "_SessionBind | None" in function "__init__"
  Line 201: Cannot access attribute "_initial_asyncpg_url" for class "PostgresAdapter*"
  Line 208: No overloads for "__init__" match the provided arguments
  Line 209: Argument of type "AsyncEngine" cannot be assigned to parameter "bind" of type "_SessionBind | None" in function "__init__"
  Line 231: "last_retryable_exception" is possibly unbound
  Line 249: "last_retryable_exception" is possibly unbound
  Line 254: "last_retryable_exception" is possibly unbound
  Line 254: Invalid exception class or object
  Line 278: Cannot assign to attribute "db" for class "PostgresAdapter*"
  Line 292: "Never" is not awaitable

[bot\game\action_processor.py] - 11 issue(s)
  Line 53: Argument missing for parameter "discord_user_id"
  Line 64: Cannot access attribute "get_location" for class "LocationManager"
  Line 68: Argument of type "GameState" cannot be assigned to parameter "guild_id" of type "str" in function "get_location_channel"
  Line 79: Cannot access attribute "get_active_events_in_location" for class "EventManager"
  Line 143: Argument of type "tuple[str, str]" cannot be assigned to parameter "user_prompt" of type "str" in function "generate_master_response"
  Line 155: Cannot access attribute "get_exit_target" for class "LocationManager"
  Line 172: Argument missing for parameter "guild_id"
  Line 203: Argument of type "GameState" cannot be assigned to parameter "guild_id" of type "str" in function "get_location_channel"
  Line 236: Cannot access attribute "perform_check" for class "RuleEngine"
  Line 297: No parameter named "message_key"
  Line 298: No parameter named "message_params"
